# Generated by Django 4.2.14 on 2024-11-03 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.JSONField()),
                ('variations', models.JSONField()),
                ('matches', models.JSONField()),
                ('results', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('search_engine', models.CharField(choices=[('DBLP', 'DBLP'), ('SEMANTIC_SCHOLAR', 'SEMANTIC_SCHOLAR'), ('WEB_OF_SCIENCE', 'WEB_OF_SCIENCE'), ('IEEE_XPLORE', 'IEEE_XPLORE'), ('SCOPUS', 'SCOPUS')], max_length=200)),
                ('paper_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
