# Generated by Django 4.2.14 on 2024-12-17 17:02

from django.db import migrations, models
import django.db.models.deletion
import scraping.infrastructure.data_export.exportable


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('paper_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('paper_title', models.CharField(max_length=200)),
                ('search_string', models.CharField(blank=True, max_length=200)),
                ('searched_from', models.JSONField(default=list)),
                ('formatted_search_string', models.CharField(blank=True, max_length=200)),
            ],
            bases=(models.Model, scraping.infrastructure.data_export.exportable.Exportable),
        ),
        migrations.CreateModel(
            name='PublicationLLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(blank=True, max_length=200)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('abstract', models.TextField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('semantic_scholar_url', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('conference_journal', models.CharField(blank=True, max_length=200)),
                ('publication_type', models.CharField(blank=True, max_length=200)),
                ('search_string', models.CharField(blank=True, max_length=200)),
                ('citation_count', models.IntegerField(default=0)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='publication.publication')),
            ],
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('paper_id', 'paper_title', 'searched_from'), name='unique_paper_id_and_title'),
        ),
    ]
