# Generated by Django 4.2.14 on 2024-12-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='publicationmetadata',
            name='doi_url',
        ),
        migrations.RemoveField(
            model_name='publicationmetadata',
            name='searched_from',
        ),
        migrations.AlterField(
            model_name='publication',
            name='formatted_search_string',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paper_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='search_string',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='abstract',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='authors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='citation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='conference_journal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='doi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='paper_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='publication_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='search_string',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationmetadata',
            name='semantic_scholar_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
